package th.ac.kmitl.science.comsci.example.models;

public class CitySubDivisionCodeMapping implements Mapping {

    @Override
    public int mapper(String name) {
        switch(name){
            case  "Phra Borom Maha Ratchawang" : return 100101;
            case  "Wang Burapha Phirom"        : return 100102;
            case  "Wat Ratchabophit"           : return 100103;
            case  "Samran Rat"                 : return 100104; 
            case  "San Chaopho Suea"           : return 100105;
            case  "Sao Chingcha"               : return 100106;
            case  "Bowon Niwet"                : return 100107;
            case  "Talat Yot"                  : return 100108;
            case  "Chana Songkhram"            : return 100109;
            case  "Ban Phan Thom"              : return 100110;
            case  "Bang Khun Phrom"            : return 100111;
            case  "Wat Sam Phraya"             : return 100112;
            case  "Dusit"                      : return 100201;
            case  "Wachiraphayaban"            : return 100202;
            case  "Suan Chit Lada"             : return 100203;
            case  "Si Yaek Maha Nak"           : return 100204;
            case  "Thanon Nakhon Chai Si"      : return 100206;
            case  "Krathum Rai"                : return 100301;
            case  "Nong Chok"                  : return 100302;
            case  "Khlong Sip"                 : return 100303;
            case  "Khlong Sip Song"            : return 100304;   
            case  "Khok Faet"                  : return 100305;
            case  "Khu Fang Nuea"              : return 100306;
            case  "Lam Phak Chi"               : return 100307;
            case  "Lam Toiting"                : return 100308;
            case  "Maha Phruettharam"          : return 100401;
            case  "Si Lom"                     : return 100402;
            case  "Suriyawong"                 : return 100403;
            case  "Bang Rak"                   : return 100404;
            case  "Si Phraya"                  : return 100405;
            case  "Anusawari"                  : return 100502;
            case  "Tha Raeng"                  : return 100508;
            case  "Khlong Chan"                : return 100601;
            case  "Hua Mak"                    : return 100608;
            case  "Rong Mueang"                : return 100701;
            case  "Wang Mai"                   : return 100702;
            case  "Pathum Wan"                 : return 100703;
            case  "Lumphini"                   : return 100704;
            case  "Pom Prap"                   : return 100801;
            case  "Wat Thep Sirin"             : return 100802;
            case  "Khlong Maha Nak"            : return 100803;
            case  "Ban Bat"                    : return 100804;
            case  "Wat Sommanat"               : return 100805;
            case  "Bang Chak"                  : return 100905;
            case  "Phra Khanong Tai"           : return 100910;
            case  "Min Buri"                   : return 101001;
            case  "Saen Saep"                  : return 101002;
            case  "Lat Krabang"                : return 101101;
            case  "Khlong Song Ton Nu"         : return 101102;
            case  "Khlong Sam Prawet"          : return 101103;
            case  "Lam Pla Thio"               : return 101104;
            case  "Thap Yao"                   : return 101105;
            case  "Khum Thong"                 : return 101106;
            case  "Chong Nonsi"                : return 101203;
            case  "Bang Phongphang"            : return 101204;
            case  "Chakkrawat"                 : return 101301;
            case  "Samphanthawong"             : return 101302;
            case  "Talat Noi"                  : return 101303;
            case  "Sam Sen Nai"                : return 101401;
            case  "Phaya Thai"                 : return 101406;
            case  "Wat Kanlaya"                : return 101501;
            case  "Hiran Ruchi"                : return 101502;
            case  "Bang Yi Ruea"               : return 101503;
            case  "Bukkhalo"                   : return 101504;
            case  "Talat Phlu"                 : return 101505;
            case  "Dao Khanong"                : return 101506;
            case  "Samre"                      : return 101507;
            case  "Wat Arun"                   : return 101601;
            case  "Wat Tha Phra"               : return 101602;
            case  "Huai Khwang"                : return 101701;
            case  "Bang Kapi"                  : return 101702;
            case  "Sam Sen Nok"                : return 101704;
            case  "Somdet Chao Phraya"         : return 101801;
            case  "Khlong San"                 : return 101802;
            case  "Bang Lamphu Lang"           : return 101803;
            case  "Khlong Ton Sai"             : return 101804;
            case  "Khlong Chak Phra"           : return 101901;
            case  "Taling Chan"                : return 101902;    
            case  "Chimphli"                   : return 101903; 
            case  "Bang Phrom"                 : return 101904;
            case  "Bang Ramat"                 : return 101905;
            case  "Bang Chueak Nang"           : return 101907;
            case  "Siri Rat"                   : return 102004;
            case  "Ban Chang Lo"               : return 102005;
            case  "Bang Khun Non"              : return 102006;    
            case  "Bang Khun Si"               : return 102007;
            case  "Arun Ammarin"               : return 102009;
            case  "Tha Kham"                   : return 102105;
            case  "Samae Dam"                  : return 102107;
            case  "Bang Wa"                    : return 102201;
            case  "Bang Duan"                  : return 102202;    
            case  "Bang Chake"                 : return 102206;
            case  "Bang Waek"                  : return 102207;
            case  "Khlong Khwang"              : return 102208;
            case  "Pak Khlong Phasi Charoe"    : return 102209;
            case  "Khuha Sawan"                : return 102210;
            case  "Nong Khaem"                 : return 102302;
            case  "Nong Khang Phlu"            : return 102303;
            case  "Rat Burana"                 : return 102401;
            case  "Bang Pakok"                 : return 102402;
            case  "Bang Phlat"                 : return 102501;
            case  "Bang O"                     : return 102502;
            case  "Bang Bamru"                 : return 102503;
            case  "Bang Yi Khan"               : return 102504;
            case  "Din Daeng"                  : return 102601;
            case  "Ratchadaphisek"             : return 102601;
            case  "Khlong Kum"                 : return 102701;
            case  "Nawamin"                    : return 102704;
            case  "Nuan Chan"                  : return 102705;
            case  "Thung Wat Don"              : return 102801;
            case  "Yan Nawa"                   : return 102802;
            case  "Thung Maha Mek"             : return 102803;  
            case  "Bang Sue"                   : return 102901;
            case  "Wong Sawang"                : return 102902;
            case  "Lat Yao"                    : return 103001;
            case  "Sena Nikhom"                : return 103002;
            case  "Chan Kasem"                 : return 103003;
            case  "Chomphon"                   : return 103004;
            case  "Chatuchak"                  : return 103005;
            case  "Bang Kho Laem"              : return 103101;  
            case  "Wat Phraya Kra"             : return 103102;   
            case  "Bang Khlo"                  : return 103103;   
            case  "Prawet"                     : return 103201;
            case  "Nong Bon"                   : return 103202;
            case  "Dokmai"                     : return 103203;
            case  "Khlong Toei"                : return 103301;
            case  "Khlong Tan"                 : return 103302;  
            case  "Phra Khanong"               : return 103003;  
            case  "Suan Luang"                 : return 103401;
            case  "On Nut "                    : return 103402;
            case  "Phatthanakan"               : return 103403;
            case  "Bang Khun Thian"            : return 103501;
            case  "Bang Kho"                   : return 103502;
            case  "Bang Mot"                   : return 103503;
            case  "Chom Thong"                 : return 103504;
            case  "Si Kan"                     : return 103602;
            case  "Don Mueang"                 : return 103604;
            case  "Sanam Bin"                  : return 103605;
            case  "Thung Phaya Thai"           : return 103701;
            case  "Thanon Phaya Thai"          : return 103702;
            case  "Thanon Phetchaburi"         : return 103703;
            case  "Makkasan"                   : return 103704;
            case  "Lat Phrao"                  : return 103801;
            case  "Chorakhe Bua"               : return 103802;
            case  "Khlong Toei Nuea"           : return 103901;
            case  "Khlong Tan Nuea"            : return 103902;
            case  "Phra Khanong Nuea"          : return 103903;
            case  "Bang Khae"                  : return 104001;
            case  "Bang Khae Nuea"             : return 104002;
            case  "Bang Phai"                  : return 104003;
            case  "Lak Song"                   : return 104004;
            case  "Thung Song Hong"            : return 104101;
            case  "Talat Bang Khen"            : return 104102;
            case  "Sai Mai"                    : return 104201;
            case  "O Ngoen"                    : return 104202;
            case  "Khlong Thanon"              : return 104203;
            case  "Khan Na Yao"                : return 104301;
            case  "Ram Inthra"                 : return 104302;
            case  "Saphan Sung "               : return 104401;
            case  "Rat Phatthana"              : return 104401;
            case  "Thap Chang"                 : return 104401;
            case  "Wang Thonglang "            : return 104501;
            case  "Saphan Song "               : return 104502;
            case  "Khlong Chaokhun Sing"       : return 104503;
            case  "Phlapphla"                  : return 104504;
            case  "Sam Wa Tawan Tok"           : return 104601;
            case  "Sam Wa Tawan Ok"            : return 104602;
            case  "Bang Chan"                  : return 104603;
            case  "Sai Kong Din"               : return 104604;
            case  "Sai Kong Din Tai"           : return 104605;
            case  "Bang Na Nuea"               : return 104702;
            case  "Bang Na Tai"                : return 104703;
            case  "Thawi Watthana"             : return 104801;
            case  "Sala Thammasop"             : return 104802;
            case  "Bang Mote"                  : return 104901;
            case  "Thung Khru"                 : return 104902;
            case  "Bang Bon Nuea"              : return 105002;
            case  "Bang Bon Tai "              : return 105003;
            case  "Khlong Bang Phran"          : return 105004;
            case  "Khlong Bang Bon"            : return 105005;
            default : return 0;
        }
    }
    
}
