package th.ac.kmitl.science.comsci.example.models;

public class CitySubDivisionName implements Mapping {

    @Override
    public int mapper(String name) {
        switch(name){
            case  "Phra Borom Maha Ratchawang" : return 1;
            case  "Wang Burapha Phirom"        : return 2;
            case  "Wat Ratchabophit"           : return 3;
            case  "Samran Rat"                 : return 4; 
            case  "San Chaopho Suea"           : return 5;
            case  "Sao Chingcha"               : return 6;
            case  "Bowon Niwet"                : return 7;
            case  "Talat Yot"                  : return 8;
            case  "Chana Songkhram"            : return 9;
            case  "Ban Phan Thom"              : return 10;
            case  "Bang Khun Phrom"            : return 11;
            case  "Wat Sam Phraya"             : return 12;
            case  "Dusit"                      : return 1;
            case  "Wachiraphayaban"            : return 2;
            case  "Suan Chit Lada"             : return 3;
            case  "Si Yaek Maha Nak"           : return 4;
            case  "Thanon Nakhon Chai Si"      : return 5;
            case  "Krathum Rai"                : return 1;
            case  "Nong Chok"                  : return 2;
            case  "Khlong Sip"                 : return 3;
            case  "Khlong Sip Song"            : return 4;   
            case  "Khok Faet"                  : return 5;
            case  "Khu Fang Nuea"              : return 6;
            case  "Lam Phak Chi"               : return 7;
            case  "Lam Toiting"                : return 8;
            case  "Maha Phruettharam"          : return 1;
            case  "Si Lom"                     : return 2;
            case  "Suriyawong"                 : return 3;
            case  "Bang Rak"                   : return 4;
            case  "Si Phraya"                  : return 5;
            case  "Anusawari"                  : return 1;
            case  "Tha Raeng"                  : return 2;
            case  "Khlong Chan"                : return 1;
            case  "Hua Mak"                    : return 2;
            case  "Rong Mueang"                : return 1;
            case  "Wang Mai"                   : return 2;
            case  "Pathum Wan"                 : return 3;
            case  "Lumphini"                   : return 4;
            case  "Pom Prap"                   : return 1;
            case  "Wat Thep Sirin"             : return 2;
            case  "Khlong Maha Nak"            : return 3;
            case  "Ban Bat"                    : return 4;
            case  "Wat Sommanat"               : return 5;
            case  "Bang Chak"                  : return 1;
            case  "Phra Khanong Tai"           : return 2;
            case  "Min Buri"                   : return 1;
            case  "Saen Saep"                  : return 2;
            case  "Lat Krabang"                : return 1;
            case  "Khlong Song Ton Nu"         : return 2;
            case  "Khlong Sam Prawet"          : return 3;
            case  "Lam Pla Thio"               : return 4;
            case  "Thap Yao"                   : return 5;
            case  "Khum Thong"                 : return 6;
            case  "Chong Nonsi"                : return 1;
            case  "Bang Phongphang"            : return 2;
            case  "Chakkrawat"                 : return 1;
            case  "Samphanthawong"             : return 2;
            case  "Talat Noi"                  : return 3;
            case  "Sam Sen Nai"                : return 1;
            case  "Phaya Thai"                 : return 2;
            case  "Wat Kanlaya"                : return 1;
            case  "Hiran Ruchi"                : return 2;
            case  "Bang Yi Ruea"               : return 3;
            case  "Bukkhalo"                   : return 4;
            case  "Talat Phlu"                 : return 5;
            case  "Dao Khanong"                : return 6;
            case  "Samre"                      : return 7;
            case  "Wat Arun"                   : return 1;
            case  "Wat Tha Phra"               : return 2;
            case  "Huai Khwang"                : return 1;
            case  "Bang Kapi"                  : return 2;
            case  "Sam Sen Nok"                : return 3;
            case  "Somdet Chao Phraya"         : return 1;
            case  "Khlong San"                 : return 2;
            case  "Bang Lamphu Lang"           : return 3;
            case  "Khlong Ton Sai"             : return 4;
            case  "Khlong Chak Phra"           : return 1;
            case  "Taling Chan"                : return 2;    
            case  "Chimphli"                   : return 3; 
            case  "Bang Phrom"                 : return 4;
            case  "Bang Ramat"                 : return 5;
            case  "Bang Chueak Nang"           : return 6;
            case  "Siri Rat"                   : return 1;
            case  "Ban Chang Lo"               : return 2;
            case  "Bang Khun Non"              : return 3;    
            case  "Bang Khun Si"               : return 4;
            case  "Arun Ammarin"               : return 5;
            case  "Tha Kham"                   : return 1;
            case  "Samae Dam"                  : return 2;
            case  "Bang Wa"                    : return 1;
            case  "Bang Duan"                  : return 2;    
            case  "Bang Chake"                 : return 3;
            case  "Bang Waek"                  : return 4;
            case  "Khlong Khwang"              : return 5;
            case  "Pak Khlong Phasi Charoe"    : return 6;
            case  "Khuha Sawan"                : return 7;
            case  "Nong Khaem"                 : return 1;
            case  "Nong Khang Phlu"            : return 2;
            case  "Rat Burana"                 : return 1;
            case  "Bang Pakok"                 : return 2;
            case  "Bang Phlat"                 : return 1;
            case  "Bang O"                     : return 2;
            case  "Bang Bamru"                 : return 3;
            case  "Bang Yi Khan"               : return 4;
            case  "Din Daeng"                  : return 1;
            case  "Ratchadaphisek"             : return 2;
            case  "Khlong Kum"                 : return 1;
            case  "Nawamin"                    : return 2;
            case  "Nuan Chan"                  : return 3;
            case  "Thung Wat Don"              : return 1;
            case  "Yan Nawa"                   : return 2;
            case  "Thung Maha Mek"             : return 3;  
            case  "Bang Sue"                   : return 1;
            case  "Wong Sawang"                : return 2;
            case  "Lat Yao"                    : return 1;
            case  "Sena Nikhom"                : return 2;
            case  "Chan Kasem"                 : return 3;
            case  "Chomphon"                   : return 4;
            case  "Chatuchak"                  : return 5;
            case  "Bang Kho Laem"              : return 1;  
            case  "Wat Phraya Kra"             : return 2;   
            case  "Bang Khlo"                  : return 3;   
            case  "Prawet"                     : return 1;
            case  "Nong Bon"                   : return 2;
            case  "Dokmai"                     : return 3;
            case  "Khlong Toei"                : return 1;
            case  "Khlong Tan"                 : return 2;  
            case  "Phra Khanong"               : return 3;  
            case  "Suan Luang"                 : return 1;
            case  "On Nut "                    : return 2;
            case  "Phatthanakan"               : return 3;
            case  "Bang Khun Thian"            : return 1;
            case  "Bang Kho"                   : return 2;
            case  "Bang Mot"                   : return 3;
            case  "Chom Thong"                 : return 4;
            case  "Si Kan"                     : return 1;
            case  "Don Mueang"                 : return 2;
            case  "Sanam Bin"                  : return 3;
            case  "Thung Phaya Thai"           : return 1;
            case  "Thanon Phaya Thai"          : return 2;
            case  "Thanon Phetchaburi"         : return 3;
            case  "Makkasan"                   : return 4;
            case  "Lat Phrao"                  : return 1;
            case  "Chorakhe Bua"               : return 2;
            case  "Khlong Toei Nuea"           : return 1;
            case  "Khlong Tan Nuea"            : return 2;
            case  "Phra Khanong Nuea"          : return 3;
            case  "Bang Khae"                  : return 1;
            case  "Bang Khae Nuea"             : return 2;
            case  "Bang Phai"                  : return 3;
            case  "Lak Song"                   : return 4;
            case  "Thung Song Hong"            : return 1;
            case  "Talat Bang Khen"            : return 2;
            case  "Sai Mai"                    : return 1;
            case  "O Ngoen"                    : return 2;
            case  "Khlong Thanon"              : return 3;
            case  "Khan Na Yao"                : return 1;
            case  "Ram Inthra"                 : return 2;
            case  "Saphan Sung "               : return 1;
            case  "Rat Phatthana"              : return 2;
            case  "Thap Chang"                 : return 3;
            case  "Wang Thonglang "            : return 1;
            case  "Saphan Song "               : return 2;
            case  "Khlong Chaokhun Sing"       : return 3;
            case  "Phlapphla"                  : return 4;
            case  "Sam Wa Tawan Tok"           : return 1;
            case  "Sam Wa Tawan Ok"            : return 2;
            case  "Bang Chan"                  : return 3;
            case  "Sai Kong Din"               : return 4;
            case  "Sai Kong Din Tai"           : return 5;
            case  "Bang Na Nuea"               : return 1;
            case  "Bang Na Tai"                : return 2;
            case  "Thawi Watthana"             : return 1;
            case  "Sala Thammasop"             : return 2;
            case  "Bang Mote"                  : return 1;
            case  "Thung Khru"                 : return 2;
            case  "Bang Bon Nuea"              : return 1;
            case  "Bang Bon Tai "              : return 2;
            case  "Khlong Bang Phran"          : return 1;
            case  "Khlong Bang Bon"            : return 2;
            default : return 0;
        }
    }
    
}
