<%@page contentType="text/html" pageEncoding="UTF-8"%>
<option value="Phra Nakhon">พระนคร</option>
<option value="Dusit">ดุสิต</option>
<option value="Nong Chok">หนองจอก</option>
<option value="Bang Ruk">บางรัก</option>
<option value="Bang Khen">บางเขน</option>
<option value="Bang Kapi">บางกะปิ</option>
<option value="Pathum Wan">ปทุมวัน</option>
<option value="Pom Prap Sattru Phai">ป้อมปราบศัตรูพ่าย</option>
<option value="Phra Khanong">พระโขนง</option>
<option value="Min Buri">มีนบุรี</option>
<option value="Lat Krabang">ลาดกระบัง</option>
<option value="Yan Nawa" >ยานนาวา</option>
<option value="Samphanthawong">สัมพันธวงศ์</option>
<option value="Phaya Thai">พญาไท</option>
<option value="Thon Buri">ธนบุรี</option>
<option value="Bangkok Yai">บางกอกใหญ่</option>
<option value="Huai Khwang">ห้วยขวาง</option>
<option value="Khlong San">คลองสาน</option>
<option value="Taling Chan">ตลิ่งชัน</option>
<option value="Bangkok Noi">บางกอกน้อย</option>
<option value="Bang Khun Thian">บางขุนเทียน</option>
<option value="Phasi Charoen">ภาษีเจริญ</option>
<option value="Nong Khaem">หนองแขม</option>
<option value= "Rat Burana">ราษฎร์บูรณะ</option>
<option value="Bang Phlat">บางพลัด</option>
<option value="Din Daeng">ดินแดง</option>
<option value="Bueng Kum">บึงกุ่ม</option>
<option value="Sathon">สาทร</option>
<option value="Bang Sue" >บางซื่อ</option>
<option value= "Chatuchak">จตุจัทร</option>
<option value="Bang Kho Laem">บางคอแหลม</option>
<option value="Prawet">ประเวศ</option>
<option value="Khlong Toei" >คลองเตย</option>
<option value="Suan Luang">สวนหลวง</option>
<option value="Chom Thong">จอมทอง</option>
<option value="Don Mueang">ดอนเมือง</option>
<option value="Ratchathewi">ราชเทวี</option>
<option value="Lat Phrao">ลาดพร้าว</option>
<option value="Watthana">วัฒนา</option>
<option value="Bang Khae">บางแค</option>
<option value= "Lak Si">หลักสี่</option>
<option value="Sai Mai">สายไหม</option>
<option value="Khan Na Yao">คันนายาว</option>
<option value="Saphan Sung">สะพานสูง</option>
<option value= "Wang Thonglang">วังทองหลาง</option>
<option value= "Khlong Sam Wa">คลองสามวา</option>
<option value="Bang Na">บางนา</option>
<option value="Thawi Watthana">ทวีวัฒนา</option>
<option value="Thung Khru">ทุ่งครุ</option>
<option value="Bang Bon">บางบอน</option>
