<%@page contentType="text/html" pageEncoding="UTF-8"%>
<option value="Bangkok">กรุงเทพ</option>
<option value="Chiang Rai">เชียงราย</option>
<option value="Chiang Mai">เชียงใหม่</option>
<option value="Nan">น่าน</option>
<option value="Phayao">พะเยา</option>
<option value="Phrae">แพร่</option>
<option value="Mae Hong Son">แม่ฮ่องสอน</option>
<option value="Lampang">ลำปาง</option>
<option value="Lamphun">ลำพูน</option>               
<option value="Uttaradit">อุตรดิตถ์</option>
<option value="Kalasin">กาฬสินธุ์</option>
<option value="Khon Kaen">ขอนแก่น</option>
<option value="Chaiyaphum">ชัยภูมิ</option>
<option value="Nakhon Phanom">นครพนม</option>
<option value="Nakhon Ratchasima">นครราชสีมา</option>
<option value="Bueng Kan">บึงกาฬ</option>
<option value="Buri Ram">บุรีรัมย์</option>
<option value="Maha Sarakham">มหาสารคาม</option>              
<option value="Mukdahan">มุกดาหาร</option>
<option value="Yasothon">ยโสธร</option>
<option value="Roi Et">ร้อยเอ็ด</option>
<option value="Loei">เลย</option>
<option value="Si Sa Ket">ศรีสะเกษ</option>
<option value="Sakon Nakhon">สกลนคร</option>
<option value="Surin">สุรินทร์</option>
<option value="Nong Khai">หนองคาย</option>
<option value="Nong Bua Lam Phu">หนองบัวลําภู</option>
<option value="Amnat Charoen">อำนาจเจริญ</option>
<option value="Udon Thani">อุดรธานี</option>               
<option value="Ubon Ratchathani">อุบลราชธานี</option>
<option value="Kamphaeng Phet">กำแพงเพชร</option>
<option value="Chai Nat">ชัยนาท</option>
<option value="Nakhon Nayok">นครนายก</option>
<option value="Nakhon Pathom">นครปฐม</option>
<option value="Nakhon Sawan">นครสวรรค์</option>
<option value="Nonthaburi">นนทบุรี</option>
<option value="Pathum Thani">ปทุมธานี</option>
<option value="Phra Nakhon Si Ayutthaya">พระนครศรีอยุธยา</option>
<option value="Phichi">พิจิตร</option>
<option value="Phitsanulok">พิษณุโลก</option>               
<option value="Phetchabunk">เพชรบูรณ์</option>
<option value="Lop Buri">ลพบุรี</option>
<option value="Samut Prakan">สมุทรปราการ</option>
<option value="Samut Songkhram">สมุทรสงคราม</option>
<option value="Samut Sakhon">สมุทรสาคร</option>
<option value="Sing Buri">สิงห์บุรี</option>
<option value="Sukhothai">สุโขทัย</option>
<option value="Suphan Buri">สุพรรณบุรี</option>               
<option value="Saraburi">สระบุรี</option>
<option value="Ang Thong">อ่างทอง</option>
<option value="Uthai Than">อุทัยธานี</option>
<option value="Chanthaburi">จันทบุรี</option>
<option value="Chachoengsao">ฉะเชิงเทรา</option>
<option value="Chon Buri">ชลบุรี</option>
<option value="Trat">ตราด</option>
<option value="Prachin Buri">ปราจีนบุรี</option>
<option value="Rayong">ระยอง</option>
<option value="Sa Kaeo">สระแก้ว</option>
<option value="Kanchanaburi">กาญจนบุรี</option>               
<option value="Tak">ตาก</option>
<option value="Prachuap Khiri Khan">ประจวบคีรีขันธ์</option>
<option value="Phetchaburi">เพชรบุรี</option>
<option value="Ratchaburi">ราชบุรี</option>
<option value="Krabi">กระบี่</option>
<option value="Chumphon">ชุมพร</option>
<option value="Trang">ตรัง</option>              
<option value="Nakhon Si Thammarat">นครศรีธรรมราช</option>
<option value="Narathiwat">นราธิวาส</option>
<option value="Pattani">ปัตตานี</option>
<option value="Phangnga">พังงา</option>
<option value="Phatthalung">พัทลุง</option>
<option value="Phuket">ภูเก็ต</option>
<option value="Yala">ยะลา</option>
<option value="Ranong">ระนอง</option>
<option value="Songkhla">สงขวา</option>               
<option value="Satun">สตูล</option>
<option value="Surat Thani">สุราษฎร์ธานี</option>
